//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SA38_MovieTicketingDBModel", "FK_Booking_Member", "Member", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SA38_MovieTicketingSystem.Member), "Booking", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SA38_MovieTicketingSystem.Booking), true)]
[assembly: EdmRelationshipAttribute("SA38_MovieTicketingDBModel", "FK_Booking_MovieSchedule", "MovieSchedule", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SA38_MovieTicketingSystem.MovieSchedule), "Booking", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SA38_MovieTicketingSystem.Booking), true)]
[assembly: EdmRelationshipAttribute("SA38_MovieTicketingDBModel", "FK_SeatAvailability_Booking", "Booking", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SA38_MovieTicketingSystem.Booking), "SeatAvailability", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SA38_MovieTicketingSystem.SeatAvailability), true)]
[assembly: EdmRelationshipAttribute("SA38_MovieTicketingDBModel", "FK_MovieSchedule_Movie", "Movie", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SA38_MovieTicketingSystem.Movie), "MovieSchedule", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SA38_MovieTicketingSystem.MovieSchedule), true)]
[assembly: EdmRelationshipAttribute("SA38_MovieTicketingDBModel", "FK_MovieSchedule_Theatre", "Theatre", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SA38_MovieTicketingSystem.Theatre), "MovieSchedule", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SA38_MovieTicketingSystem.MovieSchedule), true)]
[assembly: EdmRelationshipAttribute("SA38_MovieTicketingDBModel", "FK_MovieSchedule_Timing", "Timing", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SA38_MovieTicketingSystem.Timing), "MovieSchedule", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SA38_MovieTicketingSystem.MovieSchedule), true)]
[assembly: EdmRelationshipAttribute("SA38_MovieTicketingDBModel", "FK_Promotion_MovieSchedule", "MovieSchedule", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SA38_MovieTicketingSystem.MovieSchedule), "Promotion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SA38_MovieTicketingSystem.Promotion), true)]
[assembly: EdmRelationshipAttribute("SA38_MovieTicketingDBModel", "FK_SeatAvailability_MovieSchedule", "MovieSchedule", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SA38_MovieTicketingSystem.MovieSchedule), "SeatAvailability", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SA38_MovieTicketingSystem.SeatAvailability), true)]
[assembly: EdmRelationshipAttribute("SA38_MovieTicketingDBModel", "FK_Promotion_Restaurant", "Restaurant", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(SA38_MovieTicketingSystem.Restaurant), "Promotion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SA38_MovieTicketingSystem.Promotion), true)]

#endregion

namespace SA38_MovieTicketingSystem
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SA38_MovieTicketingDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SA38_MovieTicketingDBEntities object using the connection string found in the 'SA38_MovieTicketingDBEntities' section of the application configuration file.
        /// </summary>
        public SA38_MovieTicketingDBEntities() : base("name=SA38_MovieTicketingDBEntities", "SA38_MovieTicketingDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SA38_MovieTicketingDBEntities object.
        /// </summary>
        public SA38_MovieTicketingDBEntities(string connectionString) : base(connectionString, "SA38_MovieTicketingDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SA38_MovieTicketingDBEntities object.
        /// </summary>
        public SA38_MovieTicketingDBEntities(EntityConnection connection) : base(connection, "SA38_MovieTicketingDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Booking> Bookings
        {
            get
            {
                if ((_Bookings == null))
                {
                    _Bookings = base.CreateObjectSet<Booking>("Bookings");
                }
                return _Bookings;
            }
        }
        private ObjectSet<Booking> _Bookings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Member> Members
        {
            get
            {
                if ((_Members == null))
                {
                    _Members = base.CreateObjectSet<Member>("Members");
                }
                return _Members;
            }
        }
        private ObjectSet<Member> _Members;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Movie> Movies
        {
            get
            {
                if ((_Movies == null))
                {
                    _Movies = base.CreateObjectSet<Movie>("Movies");
                }
                return _Movies;
            }
        }
        private ObjectSet<Movie> _Movies;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MovieSchedule> MovieSchedules
        {
            get
            {
                if ((_MovieSchedules == null))
                {
                    _MovieSchedules = base.CreateObjectSet<MovieSchedule>("MovieSchedules");
                }
                return _MovieSchedules;
            }
        }
        private ObjectSet<MovieSchedule> _MovieSchedules;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Promotion> Promotions
        {
            get
            {
                if ((_Promotions == null))
                {
                    _Promotions = base.CreateObjectSet<Promotion>("Promotions");
                }
                return _Promotions;
            }
        }
        private ObjectSet<Promotion> _Promotions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Restaurant> Restaurants
        {
            get
            {
                if ((_Restaurants == null))
                {
                    _Restaurants = base.CreateObjectSet<Restaurant>("Restaurants");
                }
                return _Restaurants;
            }
        }
        private ObjectSet<Restaurant> _Restaurants;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SeatAvailability> SeatAvailabilities
        {
            get
            {
                if ((_SeatAvailabilities == null))
                {
                    _SeatAvailabilities = base.CreateObjectSet<SeatAvailability>("SeatAvailabilities");
                }
                return _SeatAvailabilities;
            }
        }
        private ObjectSet<SeatAvailability> _SeatAvailabilities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Theatre> Theatres
        {
            get
            {
                if ((_Theatres == null))
                {
                    _Theatres = base.CreateObjectSet<Theatre>("Theatres");
                }
                return _Theatres;
            }
        }
        private ObjectSet<Theatre> _Theatres;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Timing> Timings
        {
            get
            {
                if ((_Timings == null))
                {
                    _Timings = base.CreateObjectSet<Timing>("Timings");
                }
                return _Timings;
            }
        }
        private ObjectSet<Timing> _Timings;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Bookings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToBookings(Booking booking)
        {
            base.AddObject("Bookings", booking);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Members EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMembers(Member member)
        {
            base.AddObject("Members", member);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Movies EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMovies(Movie movie)
        {
            base.AddObject("Movies", movie);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MovieSchedules EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMovieSchedules(MovieSchedule movieSchedule)
        {
            base.AddObject("MovieSchedules", movieSchedule);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Promotions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPromotions(Promotion promotion)
        {
            base.AddObject("Promotions", promotion);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Restaurants EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRestaurants(Restaurant restaurant)
        {
            base.AddObject("Restaurants", restaurant);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SeatAvailabilities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSeatAvailabilities(SeatAvailability seatAvailability)
        {
            base.AddObject("SeatAvailabilities", seatAvailability);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Theatres EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTheatres(Theatre theatre)
        {
            base.AddObject("Theatres", theatre);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Timings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTimings(Timing timing)
        {
            base.AddObject("Timings", timing);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SA38_MovieTicketingDBModel", Name="Booking")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Booking : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Booking object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Booking CreateBooking(global::System.String id)
        {
            Booking booking = new Booking();
            booking.Id = id;
            return booking;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ScheduleId
        {
            get
            {
                return _ScheduleId;
            }
            set
            {
                OnScheduleIdChanging(value);
                ReportPropertyChanging("ScheduleId");
                _ScheduleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ScheduleId");
                OnScheduleIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ScheduleId;
        partial void OnScheduleIdChanging(Nullable<global::System.Int32> value);
        partial void OnScheduleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MemberId
        {
            get
            {
                return _MemberId;
            }
            set
            {
                OnMemberIdChanging(value);
                ReportPropertyChanging("MemberId");
                _MemberId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MemberId");
                OnMemberIdChanged();
            }
        }
        private global::System.String _MemberId;
        partial void OnMemberIdChanging(global::System.String value);
        partial void OnMemberIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SA38_MovieTicketingDBModel", "FK_Booking_Member", "Member")]
        public Member Member
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Member>("SA38_MovieTicketingDBModel.FK_Booking_Member", "Member").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Member>("SA38_MovieTicketingDBModel.FK_Booking_Member", "Member").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Member> MemberReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Member>("SA38_MovieTicketingDBModel.FK_Booking_Member", "Member");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Member>("SA38_MovieTicketingDBModel.FK_Booking_Member", "Member", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SA38_MovieTicketingDBModel", "FK_Booking_MovieSchedule", "MovieSchedule")]
        public MovieSchedule MovieSchedule
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MovieSchedule>("SA38_MovieTicketingDBModel.FK_Booking_MovieSchedule", "MovieSchedule").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MovieSchedule>("SA38_MovieTicketingDBModel.FK_Booking_MovieSchedule", "MovieSchedule").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MovieSchedule> MovieScheduleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MovieSchedule>("SA38_MovieTicketingDBModel.FK_Booking_MovieSchedule", "MovieSchedule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MovieSchedule>("SA38_MovieTicketingDBModel.FK_Booking_MovieSchedule", "MovieSchedule", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SA38_MovieTicketingDBModel", "FK_SeatAvailability_Booking", "SeatAvailability")]
        public EntityCollection<SeatAvailability> SeatAvailabilities
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SeatAvailability>("SA38_MovieTicketingDBModel.FK_SeatAvailability_Booking", "SeatAvailability");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SeatAvailability>("SA38_MovieTicketingDBModel.FK_SeatAvailability_Booking", "SeatAvailability", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SA38_MovieTicketingDBModel", Name="Member")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Member : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Member object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Member CreateMember(global::System.String id, global::System.String name)
        {
            Member member = new Member();
            member.Id = id;
            member.Name = name;
            return member;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NRIC
        {
            get
            {
                return _NRIC;
            }
            set
            {
                OnNRICChanging(value);
                ReportPropertyChanging("NRIC");
                _NRIC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NRIC");
                OnNRICChanged();
            }
        }
        private global::System.String _NRIC;
        partial void OnNRICChanging(global::System.String value);
        partial void OnNRICChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneNumber
        {
            get
            {
                return _PhoneNumber;
            }
            set
            {
                OnPhoneNumberChanging(value);
                ReportPropertyChanging("PhoneNumber");
                _PhoneNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhoneNumber");
                OnPhoneNumberChanged();
            }
        }
        private global::System.String _PhoneNumber;
        partial void OnPhoneNumberChanging(global::System.String value);
        partial void OnPhoneNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DOB
        {
            get
            {
                return _DOB;
            }
            set
            {
                OnDOBChanging(value);
                ReportPropertyChanging("DOB");
                _DOB = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DOB");
                OnDOBChanged();
            }
        }
        private Nullable<global::System.DateTime> _DOB;
        partial void OnDOBChanging(Nullable<global::System.DateTime> value);
        partial void OnDOBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SA38_MovieTicketingDBModel", "FK_Booking_Member", "Booking")]
        public EntityCollection<Booking> Bookings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Booking>("SA38_MovieTicketingDBModel.FK_Booking_Member", "Booking");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Booking>("SA38_MovieTicketingDBModel.FK_Booking_Member", "Booking", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SA38_MovieTicketingDBModel", Name="Movie")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Movie : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Movie object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Movie CreateMovie(global::System.Int32 id)
        {
            Movie movie = new Movie();
            movie.Id = id;
            return movie;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Rating
        {
            get
            {
                return _Rating;
            }
            set
            {
                OnRatingChanging(value);
                ReportPropertyChanging("Rating");
                _Rating = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Rating");
                OnRatingChanged();
            }
        }
        private global::System.String _Rating;
        partial void OnRatingChanging(global::System.String value);
        partial void OnRatingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContentURL
        {
            get
            {
                return _ContentURL;
            }
            set
            {
                OnContentURLChanging(value);
                ReportPropertyChanging("ContentURL");
                _ContentURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContentURL");
                OnContentURLChanged();
            }
        }
        private global::System.String _ContentURL;
        partial void OnContentURLChanging(global::System.String value);
        partial void OnContentURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Duration
        {
            get
            {
                return _Duration;
            }
            set
            {
                OnDurationChanging(value);
                ReportPropertyChanging("Duration");
                _Duration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Duration");
                OnDurationChanged();
            }
        }
        private Nullable<global::System.Int32> _Duration;
        partial void OnDurationChanging(Nullable<global::System.Int32> value);
        partial void OnDurationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private Nullable<global::System.Double> _Price;
        partial void OnPriceChanging(Nullable<global::System.Double> value);
        partial void OnPriceChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SA38_MovieTicketingDBModel", "FK_MovieSchedule_Movie", "MovieSchedule")]
        public EntityCollection<MovieSchedule> MovieSchedules
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MovieSchedule>("SA38_MovieTicketingDBModel.FK_MovieSchedule_Movie", "MovieSchedule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MovieSchedule>("SA38_MovieTicketingDBModel.FK_MovieSchedule_Movie", "MovieSchedule", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SA38_MovieTicketingDBModel", Name="MovieSchedule")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MovieSchedule : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MovieSchedule object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static MovieSchedule CreateMovieSchedule(global::System.Int32 id)
        {
            MovieSchedule movieSchedule = new MovieSchedule();
            movieSchedule.Id = id;
            return movieSchedule;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MovieId
        {
            get
            {
                return _MovieId;
            }
            set
            {
                OnMovieIdChanging(value);
                ReportPropertyChanging("MovieId");
                _MovieId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MovieId");
                OnMovieIdChanged();
            }
        }
        private Nullable<global::System.Int32> _MovieId;
        partial void OnMovieIdChanging(Nullable<global::System.Int32> value);
        partial void OnMovieIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TheatreId
        {
            get
            {
                return _TheatreId;
            }
            set
            {
                OnTheatreIdChanging(value);
                ReportPropertyChanging("TheatreId");
                _TheatreId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TheatreId");
                OnTheatreIdChanged();
            }
        }
        private Nullable<global::System.Int32> _TheatreId;
        partial void OnTheatreIdChanging(Nullable<global::System.Int32> value);
        partial void OnTheatreIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TimingId
        {
            get
            {
                return _TimingId;
            }
            set
            {
                OnTimingIdChanging(value);
                ReportPropertyChanging("TimingId");
                _TimingId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimingId");
                OnTimingIdChanged();
            }
        }
        private Nullable<global::System.Int32> _TimingId;
        partial void OnTimingIdChanging(Nullable<global::System.Int32> value);
        partial void OnTimingIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ScheduleDate
        {
            get
            {
                return _ScheduleDate;
            }
            set
            {
                OnScheduleDateChanging(value);
                ReportPropertyChanging("ScheduleDate");
                _ScheduleDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ScheduleDate");
                OnScheduleDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ScheduleDate;
        partial void OnScheduleDateChanging(Nullable<global::System.DateTime> value);
        partial void OnScheduleDateChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SA38_MovieTicketingDBModel", "FK_Booking_MovieSchedule", "Booking")]
        public EntityCollection<Booking> Bookings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Booking>("SA38_MovieTicketingDBModel.FK_Booking_MovieSchedule", "Booking");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Booking>("SA38_MovieTicketingDBModel.FK_Booking_MovieSchedule", "Booking", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SA38_MovieTicketingDBModel", "FK_MovieSchedule_Movie", "Movie")]
        public Movie Movie
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Movie>("SA38_MovieTicketingDBModel.FK_MovieSchedule_Movie", "Movie").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Movie>("SA38_MovieTicketingDBModel.FK_MovieSchedule_Movie", "Movie").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Movie> MovieReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Movie>("SA38_MovieTicketingDBModel.FK_MovieSchedule_Movie", "Movie");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Movie>("SA38_MovieTicketingDBModel.FK_MovieSchedule_Movie", "Movie", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SA38_MovieTicketingDBModel", "FK_MovieSchedule_Theatre", "Theatre")]
        public Theatre Theatre
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theatre>("SA38_MovieTicketingDBModel.FK_MovieSchedule_Theatre", "Theatre").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theatre>("SA38_MovieTicketingDBModel.FK_MovieSchedule_Theatre", "Theatre").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Theatre> TheatreReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Theatre>("SA38_MovieTicketingDBModel.FK_MovieSchedule_Theatre", "Theatre");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Theatre>("SA38_MovieTicketingDBModel.FK_MovieSchedule_Theatre", "Theatre", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SA38_MovieTicketingDBModel", "FK_MovieSchedule_Timing", "Timing")]
        public Timing Timing
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Timing>("SA38_MovieTicketingDBModel.FK_MovieSchedule_Timing", "Timing").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Timing>("SA38_MovieTicketingDBModel.FK_MovieSchedule_Timing", "Timing").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Timing> TimingReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Timing>("SA38_MovieTicketingDBModel.FK_MovieSchedule_Timing", "Timing");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Timing>("SA38_MovieTicketingDBModel.FK_MovieSchedule_Timing", "Timing", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SA38_MovieTicketingDBModel", "FK_Promotion_MovieSchedule", "Promotion")]
        public EntityCollection<Promotion> Promotions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Promotion>("SA38_MovieTicketingDBModel.FK_Promotion_MovieSchedule", "Promotion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Promotion>("SA38_MovieTicketingDBModel.FK_Promotion_MovieSchedule", "Promotion", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SA38_MovieTicketingDBModel", "FK_SeatAvailability_MovieSchedule", "SeatAvailability")]
        public EntityCollection<SeatAvailability> SeatAvailabilities
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SeatAvailability>("SA38_MovieTicketingDBModel.FK_SeatAvailability_MovieSchedule", "SeatAvailability");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SeatAvailability>("SA38_MovieTicketingDBModel.FK_SeatAvailability_MovieSchedule", "SeatAvailability", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SA38_MovieTicketingDBModel", Name="Promotion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Promotion : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Promotion object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Promotion CreatePromotion(global::System.Int32 id)
        {
            Promotion promotion = new Promotion();
            promotion.Id = id;
            return promotion;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ScheduleId
        {
            get
            {
                return _ScheduleId;
            }
            set
            {
                OnScheduleIdChanging(value);
                ReportPropertyChanging("ScheduleId");
                _ScheduleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ScheduleId");
                OnScheduleIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ScheduleId;
        partial void OnScheduleIdChanging(Nullable<global::System.Int32> value);
        partial void OnScheduleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RestaurantId
        {
            get
            {
                return _RestaurantId;
            }
            set
            {
                OnRestaurantIdChanging(value);
                ReportPropertyChanging("RestaurantId");
                _RestaurantId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RestaurantId");
                OnRestaurantIdChanged();
            }
        }
        private Nullable<global::System.Int32> _RestaurantId;
        partial void OnRestaurantIdChanging(Nullable<global::System.Int32> value);
        partial void OnRestaurantIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContentURL
        {
            get
            {
                return _ContentURL;
            }
            set
            {
                OnContentURLChanging(value);
                ReportPropertyChanging("ContentURL");
                _ContentURL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContentURL");
                OnContentURLChanged();
            }
        }
        private global::System.String _ContentURL;
        partial void OnContentURLChanging(global::System.String value);
        partial void OnContentURLChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SA38_MovieTicketingDBModel", "FK_Promotion_MovieSchedule", "MovieSchedule")]
        public MovieSchedule MovieSchedule
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MovieSchedule>("SA38_MovieTicketingDBModel.FK_Promotion_MovieSchedule", "MovieSchedule").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MovieSchedule>("SA38_MovieTicketingDBModel.FK_Promotion_MovieSchedule", "MovieSchedule").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MovieSchedule> MovieScheduleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MovieSchedule>("SA38_MovieTicketingDBModel.FK_Promotion_MovieSchedule", "MovieSchedule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MovieSchedule>("SA38_MovieTicketingDBModel.FK_Promotion_MovieSchedule", "MovieSchedule", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SA38_MovieTicketingDBModel", "FK_Promotion_Restaurant", "Restaurant")]
        public Restaurant Restaurant
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Restaurant>("SA38_MovieTicketingDBModel.FK_Promotion_Restaurant", "Restaurant").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Restaurant>("SA38_MovieTicketingDBModel.FK_Promotion_Restaurant", "Restaurant").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Restaurant> RestaurantReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Restaurant>("SA38_MovieTicketingDBModel.FK_Promotion_Restaurant", "Restaurant");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Restaurant>("SA38_MovieTicketingDBModel.FK_Promotion_Restaurant", "Restaurant", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SA38_MovieTicketingDBModel", Name="Restaurant")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Restaurant : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Restaurant object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Restaurant CreateRestaurant(global::System.Int32 id)
        {
            Restaurant restaurant = new Restaurant();
            restaurant.Id = id;
            return restaurant;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String URL
        {
            get
            {
                return _URL;
            }
            set
            {
                OnURLChanging(value);
                ReportPropertyChanging("URL");
                _URL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("URL");
                OnURLChanged();
            }
        }
        private global::System.String _URL;
        partial void OnURLChanging(global::System.String value);
        partial void OnURLChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SA38_MovieTicketingDBModel", "FK_Promotion_Restaurant", "Promotion")]
        public EntityCollection<Promotion> Promotions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Promotion>("SA38_MovieTicketingDBModel.FK_Promotion_Restaurant", "Promotion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Promotion>("SA38_MovieTicketingDBModel.FK_Promotion_Restaurant", "Promotion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SA38_MovieTicketingDBModel", Name="SeatAvailability")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SeatAvailability : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SeatAvailability object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static SeatAvailability CreateSeatAvailability(global::System.Int32 id)
        {
            SeatAvailability seatAvailability = new SeatAvailability();
            seatAvailability.Id = id;
            return seatAvailability;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ScheduleId
        {
            get
            {
                return _ScheduleId;
            }
            set
            {
                OnScheduleIdChanging(value);
                ReportPropertyChanging("ScheduleId");
                _ScheduleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ScheduleId");
                OnScheduleIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ScheduleId;
        partial void OnScheduleIdChanging(Nullable<global::System.Int32> value);
        partial void OnScheduleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SeatNumber
        {
            get
            {
                return _SeatNumber;
            }
            set
            {
                OnSeatNumberChanging(value);
                ReportPropertyChanging("SeatNumber");
                _SeatNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SeatNumber");
                OnSeatNumberChanged();
            }
        }
        private global::System.String _SeatNumber;
        partial void OnSeatNumberChanging(global::System.String value);
        partial void OnSeatNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BookingId
        {
            get
            {
                return _BookingId;
            }
            set
            {
                OnBookingIdChanging(value);
                ReportPropertyChanging("BookingId");
                _BookingId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("BookingId");
                OnBookingIdChanged();
            }
        }
        private global::System.String _BookingId;
        partial void OnBookingIdChanging(global::System.String value);
        partial void OnBookingIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SA38_MovieTicketingDBModel", "FK_SeatAvailability_Booking", "Booking")]
        public Booking Booking
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Booking>("SA38_MovieTicketingDBModel.FK_SeatAvailability_Booking", "Booking").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Booking>("SA38_MovieTicketingDBModel.FK_SeatAvailability_Booking", "Booking").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Booking> BookingReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Booking>("SA38_MovieTicketingDBModel.FK_SeatAvailability_Booking", "Booking");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Booking>("SA38_MovieTicketingDBModel.FK_SeatAvailability_Booking", "Booking", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SA38_MovieTicketingDBModel", "FK_SeatAvailability_MovieSchedule", "MovieSchedule")]
        public MovieSchedule MovieSchedule
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MovieSchedule>("SA38_MovieTicketingDBModel.FK_SeatAvailability_MovieSchedule", "MovieSchedule").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MovieSchedule>("SA38_MovieTicketingDBModel.FK_SeatAvailability_MovieSchedule", "MovieSchedule").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MovieSchedule> MovieScheduleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MovieSchedule>("SA38_MovieTicketingDBModel.FK_SeatAvailability_MovieSchedule", "MovieSchedule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MovieSchedule>("SA38_MovieTicketingDBModel.FK_SeatAvailability_MovieSchedule", "MovieSchedule", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SA38_MovieTicketingDBModel", Name="Theatre")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Theatre : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Theatre object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Theatre CreateTheatre(global::System.Int32 id)
        {
            Theatre theatre = new Theatre();
            theatre.Id = id;
            return theatre;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SA38_MovieTicketingDBModel", "FK_MovieSchedule_Theatre", "MovieSchedule")]
        public EntityCollection<MovieSchedule> MovieSchedules
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MovieSchedule>("SA38_MovieTicketingDBModel.FK_MovieSchedule_Theatre", "MovieSchedule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MovieSchedule>("SA38_MovieTicketingDBModel.FK_MovieSchedule_Theatre", "MovieSchedule", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SA38_MovieTicketingDBModel", Name="Timing")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Timing : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Timing object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Timing CreateTiming(global::System.Int32 id)
        {
            Timing timing = new Timing();
            timing.Id = id;
            return timing;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartTime
        {
            get
            {
                return _StartTime;
            }
            set
            {
                OnStartTimeChanging(value);
                ReportPropertyChanging("StartTime");
                _StartTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartTime");
                OnStartTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartTime;
        partial void OnStartTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnStartTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndTime
        {
            get
            {
                return _EndTime;
            }
            set
            {
                OnEndTimeChanging(value);
                ReportPropertyChanging("EndTime");
                _EndTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndTime");
                OnEndTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndTime;
        partial void OnEndTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnEndTimeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SA38_MovieTicketingDBModel", "FK_MovieSchedule_Timing", "MovieSchedule")]
        public EntityCollection<MovieSchedule> MovieSchedules
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MovieSchedule>("SA38_MovieTicketingDBModel.FK_MovieSchedule_Timing", "MovieSchedule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MovieSchedule>("SA38_MovieTicketingDBModel.FK_MovieSchedule_Timing", "MovieSchedule", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
